export * from './svg/alert'
export * from './svg/guess'
export * from './svg/home'
export * from './svg/how-to'
export * from './svg/notes'
export * from './svg/profile'
export * from './svg/story'
export * from './svg/suspect'